arb-dir: lib/core/localization/l10n
template-arb-file: app_ar.arb
output-localization-file: app_localizations.dart
output-dir: lib/core/localization/generated
synthetic-package: false
nullable-getter: false
untranslated-messages-file: lib/core/localization/generated/untranslated.txt
