name: {{project_name.snakeCase()}}
description: {{project_description}}
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2

  # Localization
  easy_localization: ^3.0.4

  # Navigation
  go_router: ^12.1.3

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # UI
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1
  flutter_smart_dialog: ^3.3.0
  bot_toast: ^4.0.1
  flutter_svg: ^2.0.9

  # Utils
  get_it: ^7.6.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  intl: ^0.19.0

  # Media
  image_picker: ^1.0.4
  permission_handler: ^11.1.0

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

  # Video & Audio
  agora_rtc_engine: ^6.3.0
  pusher_channels_flutter: ^2.2.1
  video_player: ^2.8.2
  chewie: ^1.7.4

  # Additional UI Packages
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  infinite_scroll_pagination: ^4.0.0
  dotted_border: ^2.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.8.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
